import { MaterialIcons } from "@expo/vector-icons";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { dashboardAlertState, filterDashboardAlerts, sortDashboardAlerts, type DashboardAlertState, type DashboardSortOption, type DashboardStatusFilter, type DashboardUrgencyFilter } from "@/mobile/src/services/alert-dashboard-state";
import type { DisasterAlert } from "@/mobile/src/types/security-data";

type Colors = { surface: string; text: string; muted: string; border: string; field: string; accent: string };
export { dashboardAlertState, type DashboardAlertState } from "@/mobile/src/services/alert-dashboard-state";

function severityColor(severity: DisasterAlert["severity"], accent: string) {
  return severity === "critical" ? "#FF5964" : severity === "high" ? "#FFB34D" : severity === "moderate" ? "#EACB5B" : accent;
}

export function AlertsDashboard({ alerts, colors, onAcknowledge }: { alerts: DisasterAlert[]; colors: Colors; onAcknowledge: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<DashboardStatusFilter>("all");
  const [urgencyFilter, setUrgencyFilter] = useState<DashboardUrgencyFilter>("all");
  const [sortOption, setSortOption] = useState<DashboardSortOption>("newest");
  const filteredAlerts = sortDashboardAlerts(filterDashboardAlerts(alerts, query, statusFilter, urgencyFilter), sortOption);
  const active = filteredAlerts.filter((alert) => dashboardAlertState(alert) === "active");
  const acknowledged = filteredAlerts.filter((alert) => dashboardAlertState(alert) === "acknowledged");
  const expired = filteredAlerts.filter((alert) => dashboardAlertState(alert) === "expired");
  const groups: { key: DashboardAlertState; label: string; items: DisasterAlert[]; icon: keyof typeof MaterialIcons.glyphMap }[] = [
    { key: "active", label: "ACTIVE", items: active, icon: "notification-important" },
    { key: "acknowledged", label: "ACKNOWLEDGED", items: acknowledged, icon: "check-circle" },
    { key: "expired", label: "EXPIRED", items: expired, icon: "history" },
  ];

  return <View>
    <Text style={[styles.heading, { color: colors.muted }]}>ALERTS DASHBOARD</Text>
    <View style={[styles.searchWrap, { borderColor: colors.border }]}><MaterialIcons name="search" size={18} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search alerts" placeholderTextColor={colors.muted} accessibilityLabel="Search alert records" style={[styles.search, { color: colors.text }]} />{query.length > 0 && <Pressable onPress={() => setQuery("")} accessibilityLabel="Clear alert search" style={({ pressed }) => [styles.clear, { opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="close" size={16} color={colors.muted} /></Pressable>}</View>
    <View style={styles.filters}>{(["all", "active", "acknowledged", "expired"] as DashboardStatusFilter[]).map((filter) => <Pressable key={filter} onPress={() => setStatusFilter(filter)} accessibilityRole="button" accessibilityState={{ selected: statusFilter === filter }} style={({ pressed }) => [styles.filter, { borderColor: statusFilter === filter ? colors.accent : colors.border, backgroundColor: statusFilter === filter ? colors.accent : "transparent", opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.filterText, { color: statusFilter === filter ? "#000" : colors.text }]}>{filter}</Text></Pressable>)}</View>
    <View style={styles.controlRow}><Text style={[styles.controlLabel, { color: colors.muted }]}>URGENCY</Text><View style={styles.controlChips}>{(["all", "critical", "high_or_critical"] as DashboardUrgencyFilter[]).map((filter) => { const selected = urgencyFilter === filter; const label = filter === "high_or_critical" ? "High +" : filter; return <Pressable key={filter} onPress={() => setUrgencyFilter(filter)} accessibilityRole="button" accessibilityState={{ selected }} style={({ pressed }) => [styles.controlChip, { borderColor: selected ? colors.accent : colors.border, backgroundColor: selected ? colors.accent : "transparent", opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.controlText, { color: selected ? "#000" : colors.text }]}>{label}</Text></Pressable>; })}</View></View>
    <View style={styles.controlRow}><Text style={[styles.controlLabel, { color: colors.muted }]}>SORT BY</Text><View style={styles.controlChips}>{(["newest", "severity", "expiry"] as DashboardSortOption[]).map((option) => { const selected = sortOption === option; return <Pressable key={option} onPress={() => setSortOption(option)} accessibilityRole="button" accessibilityState={{ selected }} style={({ pressed }) => [styles.controlChip, { borderColor: selected ? colors.accent : colors.border, backgroundColor: selected ? colors.accent : "transparent", opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.controlText, { color: selected ? "#000" : colors.text }]}>{option}</Text></Pressable>; })}</View></View>
    <Text style={[styles.results, { color: colors.muted }]}>Showing {filteredAlerts.length} of {alerts.length} alert record{alerts.length === 1 ? "" : "s"}</Text>
    <View style={styles.counts}>{groups.map((group) => <View key={group.key} style={[styles.count, { borderColor: colors.border, backgroundColor: colors.field }]}><Text style={[styles.countNumber, { color: group.key === "active" ? colors.accent : colors.text }]}>{group.items.length}</Text><Text style={[styles.countLabel, { color: colors.muted }]}>{group.label}</Text></View>)}</View>
    {groups.map((group) => <View key={group.key} style={styles.group}><View style={styles.groupHeading}><MaterialIcons name={group.icon} size={15} color={group.key === "active" ? colors.accent : colors.muted} /><Text style={[styles.groupTitle, { color: colors.text }]}>{group.label}</Text><Text style={[styles.groupCount, { color: colors.muted }]}>{group.items.length}</Text></View>{group.items.length === 0 ? <Text style={[styles.empty, { color: colors.muted }]}>No {group.label.toLowerCase()} alert records.</Text> : group.items.map((alert) => { const color = severityColor(alert.severity, colors.accent); const target = [alert.hazard ? `Hazard: ${alert.hazard}` : null, alert.target_label ? `Zone: ${alert.target_label}` : null, alert.target_radius_m ? `Radius: ${alert.target_radius_m} m` : null].filter(Boolean).join(" · "); return <View key={alert.id} style={[styles.alert, { borderColor: color, backgroundColor: colors.surface }]}><View style={[styles.dot, { backgroundColor: color }]} /><View style={{ flex: 1 }}><Text style={[styles.micro, { color }]}>{alert.severity.toUpperCase()} · {alert.type.toUpperCase()} · {alert.source.replaceAll("_", " ")}</Text><Text style={[styles.title, { color: colors.text }]}>{alert.title}</Text><Text style={[styles.detail, { color: colors.muted }]}>{alert.summary}</Text>{target.length > 0 && <Text style={[styles.meta, { color: colors.muted }]}>{target}</Text>}<Text style={[styles.meta, { color: colors.muted }]}>{group.key === "acknowledged" && alert.acknowledged_at ? `Acknowledged ${new Date(alert.acknowledged_at).toLocaleString()}` : group.key === "expired" ? `Expired ${alert.expires_at ? new Date(alert.expires_at).toLocaleString() : ""}` : `Active since ${new Date(alert.issued_at).toLocaleString()}`}</Text>{group.key === "active" && <Pressable onPress={() => onAcknowledge(alert.id)} style={[styles.ack, { borderColor: colors.accent }]}><MaterialIcons name="done" size={14} color={colors.accent} /><Text style={[styles.ackText, { color: colors.accent }]}>Acknowledge</Text></Pressable>}</View></View>; })}</View>)}</View>;
}

const styles = StyleSheet.create({ heading: { fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 24, marginBottom: 9 }, searchWrap: { height: 44, borderWidth: 1, borderRadius: 13, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 }, search: { flex: 1, fontSize: 14, fontWeight: "600", paddingVertical: 0 }, clear: { height: 28, width: 28, alignItems: "center", justifyContent: "center" }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 }, filter: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 }, filterText: { fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, controlRow: { marginTop: 12, gap: 7 }, controlLabel: { fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, controlChips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, controlChip: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 }, controlText: { fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, results: { fontSize: 11, lineHeight: 16, marginTop: 9 }, counts: { flexDirection: "row", gap: 8, marginTop: 10 }, count: { flex: 1, minHeight: 70, borderWidth: 1, borderRadius: 14, padding: 11, justifyContent: "space-between" }, countNumber: { fontSize: 22, fontWeight: "900" }, countLabel: { fontSize: 9, fontWeight: "800", letterSpacing: 0.6 }, group: { marginTop: 18 }, groupHeading: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 }, groupTitle: { fontSize: 12, fontWeight: "900", letterSpacing: 0.8 }, groupCount: { fontSize: 12, fontWeight: "700", marginLeft: "auto" }, empty: { fontSize: 12, lineHeight: 17, paddingVertical: 8 }, alert: { borderWidth: 1, borderRadius: 16, padding: 14, marginBottom: 10, flexDirection: "row", gap: 10 }, dot: { width: 8, height: 8, borderRadius: 4, marginTop: 5 }, micro: { fontSize: 10, fontWeight: "900", letterSpacing: 0.65 }, title: { fontSize: 15, fontWeight: "800", marginTop: 4, marginBottom: 4 }, detail: { fontSize: 12, lineHeight: 17 }, meta: { fontSize: 11, lineHeight: 15, marginTop: 7 }, ack: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 4, borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, marginTop: 9 }, ackText: { fontSize: 12, fontWeight: "800" } });
