import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { MaterialIcons } from "@/components/ui/vectorless-icon";
import { DISPLAY_FONT } from "@/lib/typography";

type Colors = { bg: string; surface: string; text: string; muted: string; border: string; field: string; accent: string; onAccent?: string };

const RELEASES_URL = "https://github.com/alham-rizvi/Air-mesh/releases";
const PROJECT_URL = "https://github.com/alham-rizvi/Air-mesh";

function SiteButton({ label, icon, onPress, colors, outline = false }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; onPress: () => void; colors: Colors; outline?: boolean }) {
  return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.button, { backgroundColor: outline ? colors.surface : colors.accent, borderColor: outline ? colors.border : colors.accent, opacity: pressed ? 0.76 : 1 }]}><Text style={[styles.buttonText, { color: outline ? colors.text : colors.onAccent ?? "#070909" }]}>{label}</Text><MaterialIcons name={icon} size={18} color={outline ? colors.accent : colors.onAccent ?? "#070909"} /></Pressable>;
}

function SiteCard({ icon, title, detail, colors }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; colors: Colors }) {
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.field, borderColor: colors.border }]}><MaterialIcons name={icon} size={22} color={colors.accent} /></View><Text style={[styles.cardTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.copy, { color: colors.muted }]}>{detail}</Text></View>;
}

export function PublicProjectSite({ colors, onOpenCitizen, onOpenAuthority }: { colors: Colors; onOpenCitizen: () => void; onOpenAuthority: () => void }) {
  const open = (url: string) => { void Linking.openURL(url); };
  return <View style={[styles.page, { backgroundColor: colors.bg }]}><View style={[styles.nav, { backgroundColor: colors.bg, borderBottomColor: colors.border }]}><View><Text style={[styles.wordmark, { color: colors.text, fontFamily: DISPLAY_FONT }]}>SANKET</Text><Text style={[styles.navMeta, { color: colors.accent, fontFamily: DISPLAY_FONT }]}>RESPONSE SYSTEM</Text></View><View style={styles.navActions}><Pressable onPress={onOpenCitizen} style={({ pressed }) => [styles.navLink, { opacity: pressed ? 0.68 : 1 }]}><Text style={[styles.navLinkText, { color: colors.text }]}>Citizen tools</Text></Pressable><Pressable onPress={onOpenAuthority} style={({ pressed }) => [styles.navLink, { opacity: pressed ? 0.68 : 1 }]}><Text style={[styles.navLinkText, { color: colors.accent }]}>Operator</Text></Pressable></View></View><ScrollView contentContainerStyle={styles.content}>
    <View style={[styles.hero, { backgroundColor: colors.field, borderColor: colors.border }]}><View style={styles.signalField}><View style={[styles.signalLine, { backgroundColor: colors.accent }]} /><View style={[styles.signalDot, { backgroundColor: colors.accent }]} /><View style={[styles.signalDot, styles.signalDotTwo, { backgroundColor: colors.accent }]} /></View><View style={[styles.heroPill, { borderColor: colors.accent }]}><View style={[styles.liveDot, { backgroundColor: colors.accent }]} /><Text style={[styles.pillText, { color: colors.accent, fontFamily: DISPLAY_FONT }]}>CITIZEN + OPERATOR RESPONSE</Text></View><Text style={[styles.heroTitle, { color: colors.text, fontFamily: DISPLAY_FONT }]}>CALM SIGNALS.
CLEAR ACTIONS.</Text><Text style={[styles.heroCopy, { color: colors.muted }]}>Sanket Response is a citizen-first disaster-alert workspace with local safety actions, offline coordination tools, and a separately authorized operator command surface.</Text><View style={styles.heroButtons}><SiteButton label="Open citizen tools" icon="arrow-forward" onPress={onOpenCitizen} colors={colors} /><SiteButton label="Operator console" icon="admin-panel-settings" onPress={onOpenAuthority} colors={colors} outline /></View></View>
    <Text style={[styles.kicker, { color: colors.accent, fontFamily: DISPLAY_FONT }]}>ABOUT SANKET RESPONSE</Text><Text style={[styles.sectionTitle, { color: colors.text, fontFamily: DISPLAY_FONT }]}>A response system designed around the next safe action.</Text><Text style={[styles.copy, { color: colors.muted, maxWidth: 760 }]}>Citizens can open precautions, record a local safety check-in, request help, and save an incident report without an account. The operator workspace is deliberately separate: it is restricted to authorized accounts and controls only managed Sanket server alerts.</Text>
    <View style={styles.cardGrid}><SiteCard icon="health-and-safety" title="Citizen tools" detail="Safety guidance, local incident reporting, and offline-first coordination remain available without a required login." colors={colors} /><SiteCard icon="admin-panel-settings" title="Controlled operations" detail="Authorized operators can publish, update, resolve, and monitor controlled server records with geographic targets." colors={colors} /><SiteCard icon="lock" title="Honest boundaries" detail="The system does not represent cell broadcast, ERSS dispatch, or an official government feed unless those integrations are separately approved." colors={colors} /></View>
    <View style={[styles.download, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.kicker, { color: colors.accent, fontFamily: DISPLAY_FONT }]}>DOWNLOADS</Text><Text style={[styles.downloadTitle, { color: colors.text, fontFamily: DISPLAY_FONT }]}>Published Android releases</Text><Text style={[styles.copy, { color: colors.muted }]}>Release availability is determined on the project’s GitHub Releases page. This site links there directly and does not pretend that an unpublished APK exists.</Text></View><View style={styles.downloadAction}><SiteButton label="View releases" icon="download" onPress={() => open(RELEASES_URL)} colors={colors} /><SiteButton label="Project source" icon="open-in-new" onPress={() => open(PROJECT_URL)} colors={colors} outline /></View></View>
    <View style={[styles.about, { borderTopColor: colors.border }]}><View><Text style={[styles.kicker, { color: colors.muted, fontFamily: DISPLAY_FONT }]}>PROJECT STATUS</Text><Text style={[styles.aboutTitle, { color: colors.text }]}>Sanket Response keeps the citizen and operator journeys separate.</Text></View><Text style={[styles.copy, { color: colors.muted }]}>The citizen experience stays login-free. The operator command and monitoring interface requires a deployment-authorized account. Official provider connections remain inactive until their owners provide approval and validated integration details.</Text></View>
  </ScrollView></View>;
}

const styles = StyleSheet.create({
  page: { flex: 1 }, nav: { minHeight: 76, paddingHorizontal: 38, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, wordmark: { fontSize: 19, fontWeight: "900", letterSpacing: -0.6 }, navMeta: { fontSize: 8, fontWeight: "900", letterSpacing: 1.1, marginTop: 3 }, navActions: { flexDirection: "row", gap: 18, alignItems: "center" }, navLink: { minHeight: 38, justifyContent: "center" }, navLinkText: { fontSize: 12, fontWeight: "900" }, content: { padding: 34, paddingBottom: 58, maxWidth: 1240, width: "100%", alignSelf: "center" }, hero: { minHeight: 440, borderWidth: 1, borderRadius: 28, padding: 42, overflow: "hidden" }, signalField: { ...StyleSheet.absoluteFillObject, opacity: 0.38 }, signalLine: { position: "absolute", width: 500, height: 1, right: -68, top: 164, transform: [{ rotate: "-26deg" }] }, signalDot: { position: "absolute", width: 16, height: 16, borderRadius: 8, right: 160, top: 96 }, signalDotTwo: { right: 62, top: 236 }, heroPill: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7, flexDirection: "row", gap: 7, alignItems: "center" }, liveDot: { width: 7, height: 7, borderRadius: 4 }, pillText: { fontSize: 9, fontWeight: "900", letterSpacing: 1 }, heroTitle: { fontSize: 48, lineHeight: 48, maxWidth: 600, fontWeight: "900", letterSpacing: -2, marginTop: 32 }, heroCopy: { fontSize: 15, lineHeight: 22, maxWidth: 610, marginTop: 18 }, heroButtons: { flexDirection: "row", gap: 10, marginTop: 26 }, button: { minHeight: 48, borderWidth: 1, borderRadius: 14, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, buttonText: { fontSize: 12, fontWeight: "900" }, kicker: { fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 34 }, sectionTitle: { fontSize: 28, lineHeight: 31, fontWeight: "900", letterSpacing: -1.1, marginTop: 8, maxWidth: 720 }, copy: { fontSize: 13, lineHeight: 19, marginTop: 10 }, cardGrid: { flexDirection: "row", gap: 12, marginTop: 20 }, card: { flex: 1, minHeight: 200, borderWidth: 1, borderRadius: 20, padding: 18 }, icon: { width: 42, height: 42, borderWidth: 1, borderRadius: 13, alignItems: "center", justifyContent: "center" }, cardTitle: { fontSize: 16, fontWeight: "900", marginTop: 17 }, download: { borderWidth: 1, borderRadius: 22, marginTop: 32, padding: 22, flexDirection: "row", alignItems: "center", gap: 22 }, downloadTitle: { fontSize: 23, fontWeight: "900", letterSpacing: -0.8, marginTop: 6 }, downloadAction: { minWidth: 176, gap: 8 }, about: { marginTop: 35, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 20, flexDirection: "row", gap: 30 }, aboutTitle: { fontSize: 17, fontWeight: "900", marginTop: 8, maxWidth: 400 },
});
